#配置当前服务的端口(假如没有指定端口，默认端口为8080)
server:
  port: 8001
spring:
  resources:
    static-locations: file:D:/file,classpath:static
  redis:
    host: localhost
    port: 6379
    password:
  #配置数据源对象(基于数据源可以获取到连接池对象)
  datasource:
    url: jdbc:mysql://localhost:3306/db_mi_mall?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
    hikari:
      auto-commit: true
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间
      idle-timeout: 1800000
      # 最大连接数
      maximum-pool-size: 10
      # 连接超时时间 (30秒)
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: select 1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.mall: debug
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
